"""GICS sector assignments for the _FALLBACK_UNIVERSE tickers."""

SECTOR_MAP: dict[str, str] = {
    # Information Technology
    "AAPL": "Information Technology",
    "ACN":  "Information Technology",
    "ADBE": "Information Technology",
    "ADI":  "Information Technology",
    "ADP":  "Information Technology",
    "ADSK": "Information Technology",
    "AMAT": "Information Technology",
    "AMD":  "Information Technology",
    "ANET": "Information Technology",
    "AVGO": "Information Technology",
    "CDNS": "Information Technology",
    "CRM":  "Information Technology",
    "CSCO": "Information Technology",
    "FIS":  "Information Technology",
    "FISV": "Information Technology",
    "GPN":  "Information Technology",
    "IBM":  "Information Technology",
    "INTC": "Information Technology",
    "INTU": "Information Technology",
    "KLAC": "Information Technology",
    "LRCX": "Information Technology",
    "MA":   "Information Technology",
    "MCHP": "Information Technology",
    "MSFT": "Information Technology",
    "MU":   "Information Technology",
    "NOW":  "Information Technology",
    "NVDA": "Information Technology",
    "ORCL": "Information Technology",
    "PYPL": "Information Technology",
    "QCOM": "Information Technology",
    "ROP":  "Information Technology",
    "SNPS": "Information Technology",
    "TXN":  "Information Technology",
    "V":    "Information Technology",
    # Communication Services
    "CMCSA": "Communication Services",
    "DIS":   "Communication Services",
    "GOOG":  "Communication Services",
    "GOOGL": "Communication Services",
    "META":  "Communication Services",
    "NFLX":  "Communication Services",
    "T":     "Communication Services",
    "TMUS":  "Communication Services",
    "VZ":    "Communication Services",
    # Consumer Discretionary
    "AMZN": "Consumer Discretionary",
    "BKNG": "Consumer Discretionary",
    "F":    "Consumer Discretionary",
    "GM":   "Consumer Discretionary",
    "HD":   "Consumer Discretionary",
    "LOW":  "Consumer Discretionary",
    "MCD":  "Consumer Discretionary",
    "NKE":  "Consumer Discretionary",
    "SBUX": "Consumer Discretionary",
    "TGT":  "Consumer Discretionary",
    "TJX":  "Consumer Discretionary",
    "TSLA": "Consumer Discretionary",
    # Consumer Staples
    "CL":   "Consumer Staples",
    "COST": "Consumer Staples",
    "EL":   "Consumer Staples",
    "KHC":  "Consumer Staples",
    "KO":   "Consumer Staples",
    "MDLZ": "Consumer Staples",
    "MO":   "Consumer Staples",
    "PEP":  "Consumer Staples",
    "PG":   "Consumer Staples",
    "PM":   "Consumer Staples",
    "WBA":  "Consumer Staples",
    "WMT":  "Consumer Staples",
    # Energy
    "COP": "Energy",
    "CVX": "Energy",
    "EOG": "Energy",
    "OXY": "Energy",
    "PSX": "Energy",
    "SLB": "Energy",
    "VLO": "Energy",
    "XOM": "Energy",
    # Financials
    "AFL":  "Financials",
    "AIG":  "Financials",
    "AXP":  "Financials",
    "BAC":  "Financials",
    "BK":   "Financials",
    "BLK":  "Financials",
    "C":    "Financials",
    "CB":   "Financials",
    "CME":  "Financials",
    "COF":  "Financials",
    "GS":   "Financials",
    "ICE":  "Financials",
    "JPM":  "Financials",
    "MET":  "Financials",
    "MMC":  "Financials",
    "MS":   "Financials",
    "PGR":  "Financials",
    "PNC":  "Financials",
    "SCHW": "Financials",
    "SPGI": "Financials",
    "TFC":  "Financials",
    "USB":  "Financials",
    "WFC":  "Financials",
    # Health Care
    "ABBV": "Health Care",
    "ABT":  "Health Care",
    "AMGN": "Health Care",
    "BDX":  "Health Care",
    "BIIB": "Health Care",
    "BMY":  "Health Care",
    "BSX":  "Health Care",
    "CI":   "Health Care",
    "CVS":  "Health Care",
    "DHR":  "Health Care",
    "EW":   "Health Care",
    "GILD": "Health Care",
    "ISRG": "Health Care",
    "JNJ":  "Health Care",
    "LLY":  "Health Care",
    "MCK":  "Health Care",
    "MDT":  "Health Care",
    "MRK":  "Health Care",
    "PFE":  "Health Care",
    "REGN": "Health Care",
    "SYK":  "Health Care",
    "TMO":  "Health Care",
    "UNH":  "Health Care",
    "VRTX": "Health Care",
    "ZTS":  "Health Care",
    # Industrials
    "BA":  "Industrials",
    "CAT": "Industrials",
    "CTAS": "Industrials",
    "DE":  "Industrials",
    "EMR": "Industrials",
    "FDX": "Industrials",
    "GD":  "Industrials",
    "GE":  "Industrials",
    "HON": "Industrials",
    "ITW": "Industrials",
    "LMT": "Industrials",
    "MMM": "Industrials",
    "NOC": "Industrials",
    "NSC": "Industrials",
    "RTX": "Industrials",
    "TDG": "Industrials",
    "TT":  "Industrials",
    "UNP": "Industrials",
    "UPS": "Industrials",
    "WM":  "Industrials",
    # Materials
    "DD":  "Materials",
    "ECL": "Materials",
    "LIN": "Materials",
    "SHW": "Materials",
    # Real Estate
    "CCI": "Real Estate",
    "PLD": "Real Estate",
    "PSA": "Real Estate",
    "SPG": "Real Estate",
    # Utilities
    "AEP": "Utilities",
    "D":   "Utilities",
    "DUK": "Utilities",
    "EXC": "Utilities",
    "NEE": "Utilities",
    "SO":  "Utilities",
    "XEL": "Utilities",
}
